
export const ACTIONS = {
  SEARCH: 'SEARCH',
  SEARCH_CLEAR: 'CLEAR_SEARCH',
  SEARCHTERM_CHANGED: 'SEARCHTERM_CHANGED',
  SEARCH_COMPLETE: 'SEARCH_COMPLETE',

  REQUESTING_DATA: 'REQUESTING_DATA',

  SET_ACTIVE_STOCK: 'SET_ACTIVE_STOCK',
  BUY_STOCK: 'BUY_STOCK',
  BUY_STOCK_COMPLETE: 'BUY_STOCK_COMPLETE',
  SELL_STOCK: 'SELL_STOCK',
  LOAD_PORTFOLIO: 'LOAD_PORTFOLIO',
  LOAD_PORTFOLIO_COMPLETE: 'LOAD_PORTFOLIO_COMPLETE'
};
